In [3]:
#1
try:
    x = 5 / 0
except:
    print("Error Dividing By Zero")

    
    
    

Error Dividing By Zero


In [13]:
'''2 Implement a Python program to generate all sentences where subject is in '''
sub=["Americans","Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]
res=[su+" "+ver+" "+" "+ob for su in sub for ver in verb for ob in obj]
for i in res:
    print(i)

Americans Play  Baseball
Americans Play  cricket
Americans watch  Baseball
Americans watch  cricket
Indians Play  Baseball
Indians Play  cricket
Indians watch  Baseball
Indians watch  cricket


In [18]:
'Task 2 , 1'
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
print(np.vander(x, N))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
